# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'
flutter_application_path = '../flutter-test-app'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios-test-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-test-app
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end